### ISSUE TITLE
Default Sync to Reverb to true

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/magento#7]
The dropdown that appears on every product seems to be managed here: "Sync to Reverb"

app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-install-0.1.0.php

This value should default to true. Do we need to rerun the sql or will it rerun automatically on clearing the cache?

**Comment by skwp** [comment]
It actually looks like it got defaulted to 1 here: ~/dev/magento/app/code/community/Reverb/ReverbSync/sql/reverbsync_setup/mysql4-upgrade-0.1.0-0.1.1.php

**Comment by skwp** [comment]
is anythign reading this attribute though? I don't see any code referencing it

**Comment by dunagan5887** [comment]
Reverb_ReverbSync_Helper_Sync_Product::_productIsExcludedFromSync
Line 94
$revSync = $product -> getRevSync();

The attribute is being read here. As you noted, the value should default to true for every product. If no value is defined for a product, $revSync = $product -> getRevSync(); should return null, which results in false being returned for this method (resulting in product being synced). 

Are you experiencing issues with this functionality?

**Comment by skwp** [comment]
At least one user reported that they thought they had to manually set it to true to get anything to sync. I thought it should default to true, so maybe there is confusion on their end. We'll test more internally, thanks
